# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelfDefineScreenDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelfDefineScreen(object):
    def setupUi(self, SelfDefineScreen):
        SelfDefineScreen.setObjectName("SelfDefineScreen")
        SelfDefineScreen.resize(450, 220)
        SelfDefineScreen.setMinimumSize(QtCore.QSize(450, 220))
        SelfDefineScreen.setMaximumSize(QtCore.QSize(450, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(SelfDefineScreen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(SelfDefineScreen)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.combo_Layout = QtWidgets.QComboBox(SelfDefineScreen)
        self.combo_Layout.setObjectName("combo_Layout")
        self.horizontalLayout_3.addWidget(self.combo_Layout)
        self.label_7 = QtWidgets.QLabel(SelfDefineScreen)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.combo_PointKind = QtWidgets.QComboBox(SelfDefineScreen)
        self.combo_PointKind.setObjectName("combo_PointKind")
        self.horizontalLayout_3.addWidget(self.combo_PointKind)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(SelfDefineScreen)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lab_AvailWidth = QtWidgets.QLabel(SelfDefineScreen)
        self.lab_AvailWidth.setObjectName("lab_AvailWidth")
        self.horizontalLayout.addWidget(self.lab_AvailWidth)
        self.label_5 = QtWidgets.QLabel(SelfDefineScreen)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spin_SetWidth = QtWidgets.QSpinBox(SelfDefineScreen)
        self.spin_SetWidth.setObjectName("spin_SetWidth")
        self.horizontalLayout.addWidget(self.spin_SetWidth)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(SelfDefineScreen)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lab_AvailHeight = QtWidgets.QLabel(SelfDefineScreen)
        self.lab_AvailHeight.setObjectName("lab_AvailHeight")
        self.horizontalLayout_2.addWidget(self.lab_AvailHeight)
        self.label_4 = QtWidgets.QLabel(SelfDefineScreen)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spin_SetHeight = QtWidgets.QSpinBox(SelfDefineScreen)
        self.spin_SetHeight.setObjectName("spin_SetHeight")
        self.horizontalLayout_2.addWidget(self.spin_SetHeight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(SelfDefineScreen)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelfDefineScreen)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SelfDefineScreen)
        self.buttonBox.accepted.connect(SelfDefineScreen.accept) # type: ignore
        self.buttonBox.rejected.connect(SelfDefineScreen.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelfDefineScreen)

    def retranslateUi(self, SelfDefineScreen):
        _translate = QtCore.QCoreApplication.translate
        SelfDefineScreen.setWindowTitle(_translate("SelfDefineScreen", "Dialog"))
        self.label.setText(_translate("SelfDefineScreen", "操作："))
        self.label_7.setText(_translate("SelfDefineScreen", "点阵类型："))
        self.label_2.setText(_translate("SelfDefineScreen", "可用宽度："))
        self.lab_AvailWidth.setText(_translate("SelfDefineScreen", "TextLabel"))
        self.label_5.setText(_translate("SelfDefineScreen", "设置宽度1："))
        self.label_3.setText(_translate("SelfDefineScreen", "可用高度："))
        self.lab_AvailHeight.setText(_translate("SelfDefineScreen", "TextLabel"))
        self.label_4.setText(_translate("SelfDefineScreen", "设置高度1："))
        self.label_6.setText(_translate("SelfDefineScreen", "另一数值将自动计算"))
