# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ColorMultiLine.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorMultiLine(object):
    def setupUi(self, ColorMultiLine):
        ColorMultiLine.setObjectName("ColorMultiLine")
        ColorMultiLine.resize(340, 239)
        self.gridLayout = QtWidgets.QGridLayout(ColorMultiLine)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(ColorMultiLine)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.foreground_btn = QtWidgets.QPushButton(ColorMultiLine)
        self.foreground_btn.setObjectName("foreground_btn")
        self.verticalLayout.addWidget(self.foreground_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_bgcolor = QtWidgets.QCheckBox(ColorMultiLine)
        self.checkBox_bgcolor.setText("")
        self.checkBox_bgcolor.setObjectName("checkBox_bgcolor")
        self.horizontalLayout_2.addWidget(self.checkBox_bgcolor)
        self.background_btn = QtWidgets.QPushButton(ColorMultiLine)
        self.background_btn.setObjectName("background_btn")
        self.horizontalLayout_2.addWidget(self.background_btn)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_multiLine = QtWidgets.QCheckBox(ColorMultiLine)
        self.checkBox_multiLine.setObjectName("checkBox_multiLine")
        self.horizontalLayout.addWidget(self.checkBox_multiLine)
        self.label = QtWidgets.QLabel(ColorMultiLine)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.point_spinBox = QtWidgets.QDoubleSpinBox(ColorMultiLine)
        self.point_spinBox.setObjectName("point_spinBox")
        self.horizontalLayout.addWidget(self.point_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ColorMultiLine)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)

        self.retranslateUi(ColorMultiLine)
        self.buttonBox.accepted.connect(ColorMultiLine.accept) # type: ignore
        self.buttonBox.rejected.connect(ColorMultiLine.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ColorMultiLine)

    def retranslateUi(self, ColorMultiLine):
        _translate = QtCore.QCoreApplication.translate
        ColorMultiLine.setWindowTitle(_translate("ColorMultiLine", "Dialog"))
        self.foreground_btn.setText(_translate("ColorMultiLine", "文字颜色"))
        self.background_btn.setText(_translate("ColorMultiLine", "背景颜色"))
        self.checkBox_multiLine.setText(_translate("ColorMultiLine", "多行"))
        self.label.setText(_translate("ColorMultiLine", "行距(倍)"))
