# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgSet(object):
    def setupUi(self, ProgSet):
        ProgSet.setObjectName("ProgSet")
        ProgSet.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgSet)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(ProgSet)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_bgSet = QtWidgets.QWidget()
        self.tab_bgSet.setObjectName("tab_bgSet")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_bgSet)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_chooseColor = QtWidgets.QPushButton(self.tab_bgSet)
        self.btn_chooseColor.setObjectName("btn_chooseColor")
        self.horizontalLayout.addWidget(self.btn_chooseColor)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_bgDescribe = QtWidgets.QLabel(self.tab_bgSet)
        self.label_bgDescribe.setObjectName("label_bgDescribe")
        self.verticalLayout_4.addWidget(self.label_bgDescribe)
        self.tabWidget.addTab(self.tab_bgSet, "")
        self.tab_tgSet = QtWidgets.QWidget()
        self.tab_tgSet.setObjectName("tab_tgSet")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_tgSet)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_tgSet)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tabWidget.addTab(self.tab_tgSet, "")
        self.tab_inheritProg = QtWidgets.QWidget()
        self.tab_inheritProg.setObjectName("tab_inheritProg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_inheritProg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_inheritProg)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tabWidget.addTab(self.tab_inheritProg, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProgSet)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProgSet)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(ProgSet.accept) # type: ignore
        self.buttonBox.rejected.connect(ProgSet.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProgSet)

    def retranslateUi(self, ProgSet):
        _translate = QtCore.QCoreApplication.translate
        ProgSet.setWindowTitle(_translate("ProgSet", "Dialog"))
        self.btn_chooseColor.setText(_translate("ProgSet", "选择颜色"))
        self.label_bgDescribe.setText(_translate("ProgSet", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bgSet), _translate("ProgSet", "背景设置"))
        self.label_2.setText(_translate("ProgSet", "暂不可用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tgSet), _translate("ProgSet", "节目切换触发器"))
        self.label.setText(_translate("ProgSet", "暂不可用"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inheritProg), _translate("ProgSet", "继承节目"))
