# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_IconInfoManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IconInfoManage(object):
    def setupUi(self, IconInfoManage):
        IconInfoManage.setObjectName("IconInfoManage")
        IconInfoManage.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(IconInfoManage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(IconInfoManage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(IconInfoManage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(IconInfoManage)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.remove_btn = QtWidgets.QPushButton(IconInfoManage)
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout.addWidget(self.remove_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(IconInfoManage)
        QtCore.QMetaObject.connectSlotsByName(IconInfoManage)

    def retranslateUi(self, IconInfoManage):
        _translate = QtCore.QCoreApplication.translate
        IconInfoManage.setWindowTitle(_translate("IconInfoManage", "Form"))
        self.label.setText(_translate("IconInfoManage", "管理图标信息文件"))
        self.add_btn.setText(_translate("IconInfoManage", "添加文件"))
        self.remove_btn.setText(_translate("IconInfoManage", "移除"))
